language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "4.1"
  - "4.2"
script: "npm run-script test-travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
